processo 5 iniciou no clock 0
processo 9 iniciou no clock 0
processo 1 iniciou no clock 0
processo 5 encerrou no clock 16
processo 9 encerrou no clock 16
processo 6 iniciou no clock 16
processo 10 iniciou no clock 16
processo 10 encerrou no clock 31
processo 7 iniciou no clock 31
processo 1 encerrou no clock 41
processo 4 iniciou no clock 41
processo 6 encerrou no clock 47
processo 3 iniciou no clock 47
processo 7 encerrou no clock 67
processo 8 iniciou no clock 67
processo 4 encerrou no clock 68
processo 2 iniciou no clock 68
processo 3 encerrou no clock 80
processo 8 encerrou no clock 99
processo 2 encerrou no clock 110
