#![feature(unsafe_block_in_unsafe_fn)]
#![feature(core_intrinsics)]
#![feature(layout_for_ptr)]
#![feature(alloc_layout_extra)]
#![feature(const_fn)]
#![feature(const_ptr_is_null)]
#![feature(const_ptr_offset)]
#![feature(const_mut_refs)]
#![feature(const_raw_ptr_deref)]
#![feature(const_raw_ptr_to_usize_cast)]
#![feature(const_size_of_val)]
#![feature(const_align_of_val)]
#![feature(const_alloc_layout)]
#![feature(const_result)]
#![feature(const_panic)]
#![feature(const_likely)]
#![feature(const_generics)]
#![feature(unsize)]
#![feature(coerce_unsized)]
#![feature(never_type)]
#![feature(stmt_expr_attributes)]
#![feature(dispatch_from_dyn)]
#![feature(allocator_api)]
#![deny(unsafe_op_in_unsafe_fn)]
extern crate hint;

pub mod ptr;
pub mod alloc;
