#![feature(unsafe_block_in_unsafe_fn)]
#![feature(const_fn)]
#![feature(const_mut_refs)]
#![feature(const_option)]
#![deny(unsafe_op_in_unsafe_fn)]
#![warn(clippy::all, clippy::pedantic, clippy::nursery, clippy::cargo)]
#![allow(clippy::cargo_common_metadata)]
#![allow(clippy::multiple_crate_versions)]
#![allow(clippy::wildcard_dependencies)]
#![allow(clippy::module_name_repetitions)]
pub mod lists;
