#![feature(const_fn)]
#![feature(const_mut_refs)]
#![feature(const_raw_ptr_deref)]
#![feature(const_ptr_is_null)]
#![feature(const_alloc_layout)]
#![feature(const_size_of_val)]
#![feature(const_align_of_val)]
#![feature(const_result)]
#![feature(const_panic)]
#![feature(const_unreachable_unchecked)]
#![feature(allocator_api)]
#![feature(alloc_layout_extra)]
#![feature(layout_for_ptr)]

pub mod mem;
